# Generated by Django 5.2 on 2025-05-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
