# Generated by Django 5.2 on 2025-05-01 14:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_alter_product_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('HONDA', 'Honda'), ('YAMAHA', 'Yamaha'), ('BAJAJ', 'Bajaj'), ('HERO', 'Hero'), ('TVS', 'TVS')], default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(choices=[('Koshi', 'Koshi'), ('Madhesh', 'Madhesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], max_length=100, verbose_name='Province')),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Mobile Number')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
