# Generated by Django 5.1.3 on 2025-05-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_product_bluebook_page2_product_bluebook_page9'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinfo',
            name='bike_brand',
            field=models.CharField(choices=[('HONDA', 'Honda'), ('YAMAHA', 'Yamaha'), ('BAJAJ', 'Bajaj'), ('HERO', 'Hero'), ('TVS', 'TVS')], default='HONDA', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerinfo',
            name='bike_model',
            field=models.CharField(default='Unknown Model', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerinfo',
            name='bike_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerinfo',
            name='bluebook_page2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerinfo',
            name='bluebook_page9',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
