# Generated by Django 5.1.3 on 2025-05-08 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_sellerinfo_bike_brand_sellerinfo_bike_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerinfo',
            name='bike_photo',
        ),
        migrations.RemoveField(
            model_name='sellerinfo',
            name='bluebook_page2',
        ),
        migrations.RemoveField(
            model_name='sellerinfo',
            name='bluebook_page9',
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_info', to='proj.product'),
        ),
    ]
