# Generated by Django 5.1.3 on 2025-05-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0012_alter_customer_state_bikepaymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinfo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj.product'),
        ),
        migrations.AddField(
            model_name='sellerinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
