# Generated by Django 5.1.3 on 2025-05-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0013_sellerinfo_product_sellerinfo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10, verbose_name='Gender'),
        ),
    ]
