# Generated by Django 5.1.3 on 2025-05-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0014_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('', 'Select Province'), ('Koshi Province', 'Koshi'), ('Madhesh Province', 'Madhesh'), ('Bagmati Province', 'Bagmati'), ('Gandaki Province', 'Gandaki'), ('Lumbini Province', 'Lumbini'), ('Karnali Province', 'Karnali'), ('Sudurpashchim Province', 'Sudurpashchim')], max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending'), ('reserved', 'Reserved')], default='pending', max_length=20),
        ),
    ]
