# Generated by Django 5.1.3 on 2025-05-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0016_auto_20250517_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chassis_number',
            field=models.CharField(blank=True, default='Not provided', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='Not specified', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_number',
            field=models.CharField(blank=True, default='Not provided', max_length=50),
        ),
    ]
