# Generated by Django 5.1.3 on 2025-05-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0017_product_chassis_number_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_owners',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Like New', 'Like New'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
