# Generated by Django 5.1.3 on 2025-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0018_product_number_plate_product_previous_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_plate',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
