# Generated by Django 5.1.3 on 2025-05-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0019_alter_product_chassis_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
