# Generated by Django 5.1.3 on 2025-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0021_alter_wishlist_options_wishlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
